spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/emr
    username: didbre
    password:
    driverClassName: org.postgresql.Driver

  devtools:
    restart:
      pollInterval: 1000
#  liquibase:
#    change-log: database



#logging:
#  level.root: debug